config/routes.rb
Rails.application.routes.draw do
	get '/login', to: 'session#new'
	get '/logout', to: 'sessions#destroy'
	get '/signup', to: 'user#new'

  resources :users
  resources :producers
  resources :styles
  resources :ratings
  resources :regions
  resources :grapes
  resources :countries
  resources :wines

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  root 'wines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :wines
	has_many :producers, through: :wines
	has_many :styles, through: :wines
	has_many :ratings, through: :wines
	has_many :regions
	has_many :grapes, through: :wines

	validates :name, :continent, presence: true
end

app/models/distributer.rb
class Distributer < ApplicationRecord
  has_many :wines

  validates :location, :name, presence: true
end

app/models/grape.rb
class Grape < ApplicationRecord
	has_many :wine_grapes
	has_many :wines, through: :wine_grapes

	validates :name, :type, presence: true
end

app/models/producer.rb
class Producer < ApplicationRecord
	has_many :wines

	validates :name, :website, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :wine
	belongs_to :user

	validates :score, :comment, :wine_id, :user_id, presence: true
end

app/models/region.rb
class Region < ApplicationRecord
	belongs_to :country
	has_many :wines
	has_many :styles, through: :wines

	validates :name, :country_id, presence: true
end

app/models/style.rb
class Style < ApplicationRecord
	has_many :wines
	has_many :regions, through: :wines
	has_many :countries, through: :wines

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :ratings
	has_many :wines, through: :ratings
	has_many :regions, through: :wines
	has_many :countries, through: :wines
	has_many :styles, through: :wines
	has_many :producers, through: :wines
	has_many :grapes, through: :wines
	has_secure_password

	validates :username, length: { in: 6..20 }
	validates :password, length: { minimum: 8 }, allow_nil: true

	def self.find_or_create_by_omniauth(auth_hash)
		self.where(email: auth_hash["info"]["email"]).first_or_create do |user|
			user.password = SecureRandom.hex
			user.username = auth_hash["info"]["name"]
			user.image_url = auth_hash["info"]["image"]
		end
	end
end

app/models/wine.rb
class Wine < ApplicationRecord
	belongs_to :producer
	belongs_to :region
	belongs_to :country
	belongs_to :style
	has_many :ratings
	has_many :grapes

	validates :vintage, :name, :price, :producer_id, :region_id, :country_id, :style_id, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authentication_required, only: [:show]

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/grapes_helper.rb
module GrapesHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_header.html.erb
<header>
<div class="header-container">
	
	<div class="logo">
		<h1>WineBase</h1>
	</div>
	
	<div class="session-links">
		<ul>
		<% if current_user.present? %>
			<li><p>Welcome <%=current_user.username%><img src=<%= current_user.image_url %> height="32" width="32" class="profile-image"></p></li>
			<li><%=link_to "Log Out", logout_path %></li>
		<% else %>
				<li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Log via Google", "/auth/google_oauth2" %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
		<% end%>
		</ul>
	</div>

</div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-container">
	<nav>
		<ul>
			<li>Home</li>
			<li>Your Favorite Wines</li>
			<li>Your Reviews</li>
		</ul>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="main-container">
      <%= render partial: 'layouts/sidebar' %>
      <div class="content-container">
         <%= yield %>
      </div>
    </div>
  </body>
</html>